### ISSUE TITLE
Make requires.io, coveralls, etc. options at install time

### ISSUE THREAD

**Issue by Osmose** [mozilla/sugardough#41]
Just an idea: I personally would not use the requires.io and coveralls hookups in this template, and was thinking it'd be nice if things like that were options that I could enable/disable when cookiecutter asks all those questions while generating a project. Same could go for Travis or Docker support.

Thoughts?

**Comment by peterbe** [comment]
Can cookiecutter ask boolean style quesions?

We tried to document some of the opinions of sugardough in the README. Perhaps we can add more about what it would take to rip out requires.io or coveralls.

**Comment by peterbe** [comment]
fumbled on the close button

**Comment by Osmose** [comment]
So I did some research into this. The pre- and post-generation hooks are both passed through Jinja2 with the context before being run, so we could add the logic for deleting unnecessary files (like .coveragerc) there.

The main problem is with how sugardough is developed. Because of the `fabricate-cookiecutter.py` script, it's impossible to do anything but simple variable substitution, nor is it even possible for us to have two variables with the same value because it just does a blind find and replace for all instances of the value across the project.

For example:

```yaml

language: python
python:
  - "2.7"
before_script:
  - mysql -e 'create database sugardough_db character set utf8;'
install:
  - pip install -r requirements/base.txt
  - pip install -r requirements/dev.txt
  {% if use_coveralls == 'yes' %}
  - pip install coveralls
  {% endif %}
env:
  - DEBUG=False SECRET_KEY='FOO' ALLOWED_HOSTS=localhost, DATABASE_URL=mysql://root@localhost/sugardough_db
script:
  coverage run manage.py test
after_success:
  coveralls
```

There's nothing in `fabricate-cookiecutter.py` that supports adding an `if` statement like that.
